# Generated by Django 5.0.6 on 2024-05-19 19:58

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the category name (e.g., Work, Personal, etc.)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter a description for the category', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the task', max_length=200)),
                ('due_date', models.DateField(help_text='Enter the due date for the task')),
                ('due_time', models.TimeField(blank=True, help_text='Enter the due time for the task (optional)', null=True)),
                ('additional_info', models.TextField(blank=True, help_text='Enter any additional information about the task', null=True)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], help_text='The priority level of the task', max_length=1)),
                ('completed', models.BooleanField(default=False, help_text='Indicates if the task is completed')),
                ('goal_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload a resized image related to the goal (optional)', keep_meta=True, null=True, quality=75, scale=None, size=[400, 300], upload_to='goal_images/')),
                ('goal_image_alt', models.CharField(blank=True, help_text='Describe your image', max_length=50)),
                ('category', models.ForeignKey(blank=True, help_text='The category to which the task belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.category')),
                ('user', models.ForeignKey(help_text='The user who created the task', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
