# Generated by Django 5.0.6 on 2024-05-21 17:30

import cloudinary_storage.storage
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='goal_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload a resized image related to the goal (optional)', keep_meta=True, null=True, quality=75, scale=None, size=[400, 300], storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='goal_images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='goal_image_alt',
            field=models.CharField(blank=True, help_text='Describe your image', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created the task', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
